/*
 * Created on 29 avr. 2016 ( Time 13:45:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.MetricsRegistry;
import org.demo.bean.jpa.MetricsRegistryEntity;
import org.demo.bean.jpa.ProjetEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class MetricsRegistryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public MetricsRegistryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'MetricsRegistryEntity' to 'MetricsRegistry'
	 * @param metricsRegistryEntity
	 */
	public MetricsRegistry mapMetricsRegistryEntityToMetricsRegistry(MetricsRegistryEntity metricsRegistryEntity) {
		if(metricsRegistryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		MetricsRegistry metricsRegistry = map(metricsRegistryEntity, MetricsRegistry.class);

		//--- Link mapping ( link to Projet )
		if(metricsRegistryEntity.getProjet() != null) {
			metricsRegistry.setIdProjet(metricsRegistryEntity.getProjet().getId());
		}
		return metricsRegistry;
	}
	
	/**
	 * Mapping from 'MetricsRegistry' to 'MetricsRegistryEntity'
	 * @param metricsRegistry
	 * @param metricsRegistryEntity
	 */
	public void mapMetricsRegistryToMetricsRegistryEntity(MetricsRegistry metricsRegistry, MetricsRegistryEntity metricsRegistryEntity) {
		if(metricsRegistry == null) {
			return;
		}

		//--- Generic mapping 
		map(metricsRegistry, metricsRegistryEntity);

		//--- Link mapping ( link : metricsRegistry )
		if( hasLinkToProjet(metricsRegistry) ) {
			ProjetEntity projet1 = new ProjetEntity();
			projet1.setId( metricsRegistry.getIdProjet() );
			metricsRegistryEntity.setProjet( projet1 );
		} else {
			metricsRegistryEntity.setProjet( null );
		}

	}
	
	/**
	 * Verify that Projet id is valid.
	 * @param Projet Projet
	 * @return boolean
	 */
	private boolean hasLinkToProjet(MetricsRegistry metricsRegistry) {
		if(metricsRegistry.getIdProjet() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}