/*
 * Created on 29 avr. 2016 ( Time 13:45:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Projet;
import org.demo.bean.jpa.ProjetEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ProjetServiceMapperTest {

	private ProjetServiceMapper projetServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		projetServiceMapper = new ProjetServiceMapper();
		projetServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ProjetEntity' to 'Projet'
	 * @param projetEntity
	 */
	@Test
	public void testMapProjetEntityToProjet() {
		// Given
		ProjetEntity projetEntity = new ProjetEntity();
		projetEntity.setNom(mockValues.nextInteger());
		projetEntity.setCreateur(mockValues.nextInteger());
		projetEntity.setCommantaires(mockValues.nextInteger());
		projetEntity.setDateCreation(mockValues.nextInteger());
		projetEntity.setDateModification(mockValues.nextInteger());
		
		// When
		Projet projet = projetServiceMapper.mapProjetEntityToProjet(projetEntity);
		
		// Then
		assertEquals(projetEntity.getNom(), projet.getNom());
		assertEquals(projetEntity.getCreateur(), projet.getCreateur());
		assertEquals(projetEntity.getCommantaires(), projet.getCommantaires());
		assertEquals(projetEntity.getDateCreation(), projet.getDateCreation());
		assertEquals(projetEntity.getDateModification(), projet.getDateModification());
	}
	
	/**
	 * Test : Mapping from 'Projet' to 'ProjetEntity'
	 */
	@Test
	public void testMapProjetToProjetEntity() {
		// Given
		Projet projet = new Projet();
		projet.setNom(mockValues.nextInteger());
		projet.setCreateur(mockValues.nextInteger());
		projet.setCommantaires(mockValues.nextInteger());
		projet.setDateCreation(mockValues.nextInteger());
		projet.setDateModification(mockValues.nextInteger());

		ProjetEntity projetEntity = new ProjetEntity();
		
		// When
		projetServiceMapper.mapProjetToProjetEntity(projet, projetEntity);
		
		// Then
		assertEquals(projet.getNom(), projetEntity.getNom());
		assertEquals(projet.getCreateur(), projetEntity.getCreateur());
		assertEquals(projet.getCommantaires(), projetEntity.getCommantaires());
		assertEquals(projet.getDateCreation(), projetEntity.getDateCreation());
		assertEquals(projet.getDateModification(), projetEntity.getDateModification());
	}

}