/*
 * Created on 29 avr. 2016 ( Time 14:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class MetricsRegistry implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer idProjet;


    private Integer nom;


    private Date dateCreation;


    private Date dateModification;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIdProjet( Integer idProjet ) {
        this.idProjet = idProjet;
    }
    public Integer getIdProjet() {
        return this.idProjet;
    }

    public void setNom( Integer nom ) {
        this.nom = nom;
    }
    public Integer getNom() {
        return this.nom;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateModification( Date dateModification ) {
        this.dateModification = dateModification;
    }
    public Date getDateModification() {
        return this.dateModification;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(idProjet);
        sb.append("|");
        sb.append(nom);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateModification);
        return sb.toString(); 
    } 


}
