/*
 * Created on 29 avr. 2016 ( Time 14:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Projet implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer nom;


    private Integer createur;


    private Integer commantaires;


    private Integer dateCreation;


    private Integer dateModification;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNom( Integer nom ) {
        this.nom = nom;
    }
    public Integer getNom() {
        return this.nom;
    }

    public void setCreateur( Integer createur ) {
        this.createur = createur;
    }
    public Integer getCreateur() {
        return this.createur;
    }

    public void setCommantaires( Integer commantaires ) {
        this.commantaires = commantaires;
    }
    public Integer getCommantaires() {
        return this.commantaires;
    }

    public void setDateCreation( Integer dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Integer getDateCreation() {
        return this.dateCreation;
    }

    public void setDateModification( Integer dateModification ) {
        this.dateModification = dateModification;
    }
    public Integer getDateModification() {
        return this.dateModification;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(nom);
        sb.append("|");
        sb.append(createur);
        sb.append("|");
        sb.append(commantaires);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateModification);
        return sb.toString(); 
    } 


}
