/*
 * JUnit test case for bean MetricsRegistry
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.MetricsRegistry ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean MetricsRegistry
 * 
 * @author Telosys Tools Generator
 *
 */
public class MetricsRegistryTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class MetricsRegistry getters and setters ..." );
		
		MetricsRegistry metricsRegistry = new MetricsRegistry();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		metricsRegistry.setId( integerValue ) ;
		Assert.assertTrue( integerValue == metricsRegistry.getId() ) ;

		//--- Test setter/getter for field "idProjet"  ( type : Integer )
		// System.out.println(" checking field idProjet ..." );
		metricsRegistry.setIdProjet( integerValue ) ;
		Assert.assertTrue( integerValue == metricsRegistry.getIdProjet() ) ;

		//--- Test setter/getter for field "nom"  ( type : Integer )
		// System.out.println(" checking field nom ..." );
		metricsRegistry.setNom( integerValue ) ;
		Assert.assertTrue( integerValue == metricsRegistry.getNom() ) ;

		//--- Test setter/getter for field "dateCreation"  ( type : Date )
		// System.out.println(" checking field dateCreation ..." );
		metricsRegistry.setDateCreation( dateValue ) ;
		Assert.assertTrue( dateValue.equals( metricsRegistry.getDateCreation() ) );

		//--- Test setter/getter for field "dateModification"  ( type : Date )
		// System.out.println(" checking field dateModification ..." );
		metricsRegistry.setDateModification( dateValue ) ;
		Assert.assertTrue( dateValue.equals( metricsRegistry.getDateModification() ) );

		
	}



}
