/*
 * JUnit test case for bean Projet
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.Projet ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean Projet
 * 
 * @author Telosys Tools Generator
 *
 */
public class ProjetTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class Projet getters and setters ..." );
		
		Projet projet = new Projet();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		projet.setId( integerValue ) ;
		Assert.assertTrue( integerValue == projet.getId() ) ;

		//--- Test setter/getter for field "nom"  ( type : Integer )
		// System.out.println(" checking field nom ..." );
		projet.setNom( integerValue ) ;
		Assert.assertTrue( integerValue == projet.getNom() ) ;

		//--- Test setter/getter for field "createur"  ( type : Integer )
		// System.out.println(" checking field createur ..." );
		projet.setCreateur( integerValue ) ;
		Assert.assertTrue( integerValue == projet.getCreateur() ) ;

		//--- Test setter/getter for field "commantaires"  ( type : Integer )
		// System.out.println(" checking field commantaires ..." );
		projet.setCommantaires( integerValue ) ;
		Assert.assertTrue( integerValue == projet.getCommantaires() ) ;

		//--- Test setter/getter for field "dateCreation"  ( type : Integer )
		// System.out.println(" checking field dateCreation ..." );
		projet.setDateCreation( integerValue ) ;
		Assert.assertTrue( integerValue == projet.getDateCreation() ) ;

		//--- Test setter/getter for field "dateModification"  ( type : Integer )
		// System.out.println(" checking field dateModification ..." );
		projet.setDateModification( integerValue ) ;
		Assert.assertTrue( integerValue == projet.getDateModification() ) ;

		
	}



}
