/*
 * Created on 29 avr. 2016 ( Time 13:45:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "metrics_registry"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="metrics_registry", catalog="metrics" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MetricsRegistryEntity.countAll", query="SELECT COUNT(x) FROM MetricsRegistryEntity x" )
} )
public class MetricsRegistryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom")
    private Integer    nom          ;

    @Temporal(TemporalType.DATE)
    @Column(name="date_creation")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="date_modification")
    private Date       dateModification ;

	// "idProjet" (column "id_projet") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="metricsRegistry", targetEntity=TimersEntity.class)
    private List<TimersEntity> listOfTimers;

    @ManyToOne
    @JoinColumn(name="id_projet", referencedColumnName="id")
    private ProjetEntity projet      ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MetricsRegistryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nom ( INT ) 
    public void setNom( Integer nom ) {
        this.nom = nom;
    }
    public Integer getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : date_creation ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : date_modification ( DATE ) 
    public void setDateModification( Date dateModification ) {
        this.dateModification = dateModification;
    }
    public Date getDateModification() {
        return this.dateModification;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTimers( List<TimersEntity> listOfTimers ) {
        this.listOfTimers = listOfTimers;
    }
    public List<TimersEntity> getListOfTimers() {
        return this.listOfTimers;
    }

    public void setProjet( ProjetEntity projet ) {
        this.projet = projet;
    }
    public ProjetEntity getProjet() {
        return this.projet;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateModification);
        return sb.toString(); 
    } 

}
