/*
 * Created on 29 avr. 2016 ( Time 13:45:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "projet"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="projet", catalog="metrics" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ProjetEntity.countAll", query="SELECT COUNT(x) FROM ProjetEntity x" )
} )
public class ProjetEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom")
    private Integer    nom          ;

    @Column(name="createur")
    private Integer    createur     ;

    @Column(name="commantaires")
    private Integer    commantaires ;

    @Column(name="date_creation")
    private Integer    dateCreation ;

    @Column(name="date_modification")
    private Integer    dateModification ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="projet", targetEntity=MetricsRegistryEntity.class)
    private List<MetricsRegistryEntity> listOfMetricsRegistry;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProjetEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nom ( INT ) 
    public void setNom( Integer nom ) {
        this.nom = nom;
    }
    public Integer getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : createur ( INT ) 
    public void setCreateur( Integer createur ) {
        this.createur = createur;
    }
    public Integer getCreateur() {
        return this.createur;
    }

    //--- DATABASE MAPPING : commantaires ( INT ) 
    public void setCommantaires( Integer commantaires ) {
        this.commantaires = commantaires;
    }
    public Integer getCommantaires() {
        return this.commantaires;
    }

    //--- DATABASE MAPPING : date_creation ( INT ) 
    public void setDateCreation( Integer dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Integer getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : date_modification ( INT ) 
    public void setDateModification( Integer dateModification ) {
        this.dateModification = dateModification;
    }
    public Integer getDateModification() {
        return this.dateModification;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfMetricsRegistry( List<MetricsRegistryEntity> listOfMetricsRegistry ) {
        this.listOfMetricsRegistry = listOfMetricsRegistry;
    }
    public List<MetricsRegistryEntity> getListOfMetricsRegistry() {
        return this.listOfMetricsRegistry;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(createur);
        sb.append("|");
        sb.append(commantaires);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateModification);
        return sb.toString(); 
    } 

}
