/*
 * Created on 29 avr. 2016 ( Time 14:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.MetricsRegistry;

/**
 * Business Service Interface for entity MetricsRegistry.
 */
public interface MetricsRegistryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	MetricsRegistry findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MetricsRegistry> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MetricsRegistry save(MetricsRegistry entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MetricsRegistry update(MetricsRegistry entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MetricsRegistry create(MetricsRegistry entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
