/*
 * Created on 29 avr. 2016 ( Time 14:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Projet;

/**
 * Business Service Interface for entity Projet.
 */
public interface ProjetService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Projet findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Projet> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Projet save(Projet entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Projet update(Projet entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Projet create(Projet entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
