/*
 * Created on 29 avr. 2016 ( Time 14:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Timers;

/**
 * Business Service Interface for entity Timers.
 */
public interface TimersService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Timers findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Timers> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Timers save(Timers entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Timers update(Timers entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Timers create(Timers entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
