/*
 * Created on 29 avr. 2016 ( Time 14:11:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.Timers;
import org.demo.web.common.ListItem;

public class TimersListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TimersListItem(Timers timers) {
		super();

		this.value = ""
			 + timers.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = timers.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
