/*
 * JUnit test case for MetricsRegistry caching service
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.cache;


import org.demo.bean.MetricsRegistry ;
import org.demo.cache.MetricsRegistryCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for MetricsRegistry caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class MetricsRegistryCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(MetricsRegistry metricsRegistry) {
		metricsRegistry.setId( 1 ) ;
		metricsRegistry.setIdProjet( 1 ) ;
		metricsRegistry.setNom( 1 ) ;
		metricsRegistry.setDateCreation( now ) ;
		metricsRegistry.setDateModification( now ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class MetricsRegistryCache ..." );
		
		MetricsRegistry metricsRegistry = new MetricsRegistry();
		populate(metricsRegistry);
		System.out.println("Entity populated : " + metricsRegistry );
		
		MetricsRegistryCache.putMetricsRegistry(metricsRegistry) ;	// Store in cache	
		
		MetricsRegistry metricsRegistry2 = MetricsRegistryCache.getMetricsRegistry( metricsRegistry.getId() );
		Assert.assertTrue( metricsRegistry == metricsRegistry2 ) ; // Same instance
		
		MetricsRegistryCache.removeMetricsRegistry(  metricsRegistry.getId() ) ; // Remove from cache	
		
		MetricsRegistry metricsRegistry3 = MetricsRegistryCache.getMetricsRegistry( metricsRegistry.getId() );
		Assert.assertTrue( null == metricsRegistry3 ) ; // Not in cache
		
	}
}
