/*
 * JUnit test case for Projet caching service
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.cache;


import org.demo.bean.Projet ;
import org.demo.cache.ProjetCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Projet caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ProjetCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(Projet projet) {
		projet.setId( 1 ) ;
		projet.setNom( 1 ) ;
		projet.setCreateur( 1 ) ;
		projet.setCommantaires( 1 ) ;
		projet.setDateCreation( 1 ) ;
		projet.setDateModification( 1 ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class ProjetCache ..." );
		
		Projet projet = new Projet();
		populate(projet);
		System.out.println("Entity populated : " + projet );
		
		ProjetCache.putProjet(projet) ;	// Store in cache	
		
		Projet projet2 = ProjetCache.getProjet( projet.getId() );
		Assert.assertTrue( projet == projet2 ) ; // Same instance
		
		ProjetCache.removeProjet(  projet.getId() ) ; // Remove from cache	
		
		Projet projet3 = ProjetCache.getProjet( projet.getId() );
		Assert.assertTrue( null == projet3 ) ; // Not in cache
		
	}
}
