/*
 * JUnit test case for Timers caching service
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.cache;


import org.demo.bean.Timers ;
import org.demo.cache.TimersCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Timers caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class TimersCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(Timers timers) {
		timers.setId( 1 ) ;
		timers.setIdMetricsRegistry( 1 ) ;
		timers.setNom( "A" ) ;
		timers.setCount( "A" ) ;
		timers.setMeanRate( 12.345 ) ;
		timers.setOneMinuteRate( 12.345 ) ;
		timers.setFiveMinuteRate( 12.345 ) ;
		timers.setFifteenMinuteRate( 12.345 ) ;
		timers.setMin( "A" ) ;
		timers.setMax( "A" ) ;
		timers.setMean( 12.345 ) ;
		timers.setStddev( 1 ) ;
		timers.setMedian( 12.345 ) ;
		timers.setSeventyFivePercent( 12.345 ) ;
		timers.setNinetyFivePercent( 12.345 ) ;
		timers.setNinetyHeightPercent( 12.345 ) ;
		timers.setNinetyNinePercent( 12.345 ) ;
		timers.setNinetyNinePercentPointNine( 12.345 ) ;
		timers.setDateCreation( now ) ;
		timers.setDateModification( now ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class TimersCache ..." );
		
		Timers timers = new Timers();
		populate(timers);
		System.out.println("Entity populated : " + timers );
		
		TimersCache.putTimers(timers) ;	// Store in cache	
		
		Timers timers2 = TimersCache.getTimers( timers.getId() );
		Assert.assertTrue( timers == timers2 ) ; // Same instance
		
		TimersCache.removeTimers(  timers.getId() ) ; // Remove from cache	
		
		Timers timers3 = TimersCache.getTimers( timers.getId() );
		Assert.assertTrue( null == timers3 ) ; // Not in cache
		
	}
}
