/*
 * Very basic JavaBean cache
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.MetricsRegistry ;

/**
 * Very basic cache for MetricsRegistry instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class MetricsRegistryCache
{
	private final static Map<String,MetricsRegistry> cache = new Hashtable<String,MetricsRegistry>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given MetricsRegistry instance in the cache
	 * @param MetricsRegistry instance to be stored
	 */
	public final static void putMetricsRegistry(MetricsRegistry metricsRegistry ) {
		String key = getKey( metricsRegistry.getId() ) ;
		cache.put(key, metricsRegistry );
	}
	
	/**
	 * Get the MetricsRegistry instance for the given primary key
     * @param id 
	 * @return the MetricsRegistry instance (or null if none)
	 */
	public final static MetricsRegistry getMetricsRegistry( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the MetricsRegistry associated with the given primary key
     * @param id 
	 */
	public final static void removeMetricsRegistry ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given MetricsRegistry from the cache using its primary key
	 * @param MetricsRegistry instance to be removed
	 */
	public final static void removeMetricsRegistry (MetricsRegistry metricsRegistry ) { 
		String key = getKey( metricsRegistry.getId() ) ;
		cache.remove(key);
	}

}
