/*
 * Very basic JavaBean cache
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.Projet ;

/**
 * Very basic cache for Projet instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class ProjetCache
{
	private final static Map<String,Projet> cache = new Hashtable<String,Projet>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given Projet instance in the cache
	 * @param Projet instance to be stored
	 */
	public final static void putProjet(Projet projet ) {
		String key = getKey( projet.getId() ) ;
		cache.put(key, projet );
	}
	
	/**
	 * Get the Projet instance for the given primary key
     * @param id 
	 * @return the Projet instance (or null if none)
	 */
	public final static Projet getProjet( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Projet associated with the given primary key
     * @param id 
	 */
	public final static void removeProjet ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Projet from the cache using its primary key
	 * @param Projet instance to be removed
	 */
	public final static void removeProjet (Projet projet ) { 
		String key = getKey( projet.getId() ) ;
		cache.remove(key);
	}

}
