/*
 * Very basic JavaBean cache
 * Created on 29 avr. 2016 ( Date ISO 2016-04-29 - Time 13:45:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.Timers ;

/**
 * Very basic cache for Timers instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class TimersCache
{
	private final static Map<String,Timers> cache = new Hashtable<String,Timers>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given Timers instance in the cache
	 * @param Timers instance to be stored
	 */
	public final static void putTimers(Timers timers ) {
		String key = getKey( timers.getId() ) ;
		cache.put(key, timers );
	}
	
	/**
	 * Get the Timers instance for the given primary key
     * @param id 
	 * @return the Timers instance (or null if none)
	 */
	public final static Timers getTimers( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Timers associated with the given primary key
     * @param id 
	 */
	public final static void removeTimers ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Timers from the cache using its primary key
	 * @param Timers instance to be removed
	 */
	public final static void removeTimers (Timers timers ) { 
		String key = getKey( timers.getId() ) ;
		cache.remove(key);
	}

}
